version: 2.1

jobs:
  'node-lts':
    docker:
      # trunk-ignore(checkov/CKV_CIRCLECIPIPELINES_2)
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Run tests
          command: yarn test

  'node-current':
    docker:
      # trunk-ignore(checkov/CKV_CIRCLECIPIPELINES_2)
      - image: cimg/node:current
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2
  build:
    jobs:
      - 'node-lts'
      - 'node-current'
